UofA-Blueprint/DishZero

- .github/PULL_REQUREST_TEMPLATE.md
- CONTRIBUTING.md
Add contributing documentation
- Style
- Tests
- UI
> docs: add contributing docs

- package-lock.json
- package.json
- src/App.tsx
Adds firebase given code and firebase configurations
Closes #19
> Firebase additions

- firebase/.firebaserc
- firebase/README.md
- firebase/firebase.json
- firebase/firestore.indexes.json
- firebase/firestore.rules
Update firebase security rules to prevent users without proper permissions from creating check-in events #86 
+ Create a base security rule for the firestore app
- Style
- Tests
- UI
> Auth: Database: Implement permissions check for creating check-in events

- app/src/widgets/scanner.tsx
> fix: facing mode settings

- app/src/widgets/scanner.tsx
> Fix facing mode

- .gitignore
- package-lock.json
- package.json
- server/package-lock.json
- server/package.json
#150 
Added `concurrently` to start the server and client simultaneously using `npm run dev` while in the server directory. 
- Style
- Tests
- UI
> added concurrently module

- app/src/firebase.tsx
- app/src/routes/home.tsx
- app/src/routes/index.tsx
- app/src/widgets/sidebar.tsx
Prevent sidebar options from appearing for users with improper permissions
- Style
- Tests
- UI
> feat: hide sidebar options from appearing for certain users

- server/controllers/updateConfigController.js
- server/index.js
- server/routes/scheduledJobs.js
- server/routes/updateConfig.js
- server/services/remoteConfig.js
Adds endpoints to update the following fields in the Remote Config:
- userEmailReturnNotificationHourThreshold: Users who have held a dish for x hours will get the notification when the job runs
- userEmailReturnNotificationJob: Cron string describing the repetition frequency of Notification Job.
- Style
- Tests
- UI
> feat: Implement configuration for dish return

- app/src/routes/misc.tsx
> add misc pages

- app/src/features/api.tsx
- app/src/firebase.tsx
- app/src/index.tsx
- app/src/routes/borrow.tsx
- app/src/routes/index.tsx
> cleanup code and add error 404

- app/src/routes/misc.tsx
> remove redux

- app/src/routes/index.tsx
- app/src/routes/misc.tsx
Implement 404 page, including setting up its route.
- Style
- Tests
- UI
> feat: Implement 404 page

- app/package-lock.json
- app/public/index.html
- app/src/routes/misc.tsx
- app/src/styles/error404.css
Style the Error404 page according to the hi-fi mockups.
- Style
- Tests
- UI
**Screenshots (after UI update)**
> ui/style: style Error404 page

- .gitignore
- app/src/admin/adminApi.ts
- app/src/admin/dishList.tsx
- server/controllers/dishDataController.js
- server/index.js
- server/model/dish.js
- server/model/transaction.js
- server/package-lock.json
- server/package.json
- server/routes/dishData.js
- server/services/dishService.js
- server/services/firestoreService.js
- server/services/transactionService.js
- server/view_model/dishTableVm.js
Add the endpoint for getting the data for all the dishes.
- Style
- Tests
- UI
> feat: add admin endpoint for dish data

- backend/src/controllers/transactions.ts
Implemented get all transactions in the transactions controller
- Style
- Tests
- UI
> implemented get all transactions

- .gitignore
- backend/package.json
- backend/src/app.ts
- backend/src/controllers/auth.ts
- backend/src/controllers/dish.ts
- backend/src/controllers/transactions.ts
- backend/src/controllers/users.ts
- backend/src/middlewares/auth.ts
- backend/src/routes/auth.ts
- backend/yarn.lock
- testbench/scripts/README.md
- testbench/scripts/get-dishes.sh
- testbench/scripts/get-dishtrans.sh
- testbench/scripts/get-session-token.sh
- testbench/scripts/get-transactions.sh
- testbench/scripts/get_tokens.py
- testbench/scripts/requirements.txt
Added scripts for sending requests to the login, transactions, and dish endpoints.
- Style
- Tests
- UI
> test: scripts for testing end points

- app/package-lock.json
- app/package.json
- app/src/routes/login.tsx
- package-lock.json
- package.json
Fixed Login Flicker by adding a loader-spinner while firebase is reading the auth state
- Style
- Tests
- UI
> Login flicker fixed by adding loader

- backend/README.md
- backend/src/controllers/dish.ts
- backend/src/middlewares/auth.ts
- backend/src/models/dish.ts
- backend/src/models/transaction.ts
- backend/src/routes/dish.ts
- backend/src/services/dish.ts
- backend/src/services/qrCode.ts
- backend/src/services/transactions.ts
- testbench/scripts/get_tokens.py
> feat: Borrow and Return Dish

- backend/README.md
- backend/src/controllers/dish.ts
- backend/src/models/dish.ts
- backend/src/models/transaction.ts
- backend/src/services/dish.ts
- testbench/scripts/return-dish.sh
> fix: add condition logic to return dish

- backend/src/controllers/users.ts
- backend/src/middlewares/auth.ts
- backend/src/services/dish.ts
Now with this change. you can just update the role in the firebase user collection and it will elevate the permissions of the user. This will ease the development for the frontend team not able to change the role for testing.
> fix: override user role in middleware

- backend/src/controllers/dish.ts
- backend/src/services/transactions.ts
- backend/src/services/users.ts
- backend/tsconfig.json
Only admin and volunteer can only return a dish
> fix: only admin & volunteer can return dish

- app/package-lock.json
- app/package.json
- app/src/routes/home.tsx
> fixed reload page and qr code position

- backend/README.md
- backend/src/controllers/dish.ts
- backend/src/controllers/users.ts
- backend/src/models/transaction.ts
- backend/src/services/transactions.ts
- testbench/scripts/get-users.sh
> user by id

- app/src/routes/borrow.tsx
This PR implements borrow functionality after a user is redirected from the dishzero wix website.
Additionally, modals are created for the confirm, success, and fail scenarios (see Figma)
- Style
- Tests
- UI
> feat: implemented borrow functionality from wix redirect

- backend/src/models/dish.ts
- backend/src/services/dish.ts
> add borrowed at

- app/src/admin/users.tsx
fixed a bug where going from user page to admin page would instead go to home page
- Style
- Tests
- UI
> fixed url to admin page

- app/package-lock.json
- app/src/contexts/AuthContext.tsx
- app/src/routes/admin.tsx
- app/src/routes/home.tsx
- app/src/routes/return.tsx
- app/src/widgets/dishcard.tsx
- Fix error in authContext where `data` was undefined on the first render, causing the app to crash 
- Modify axios calls to correctly call backend URL. without this, it tries to call `app.dishzero.ca.api.dishzero.ca/api/....`
> fix homepage

- app/src/widgets/sidebar.tsx
> Auto close sidebar

- app/src/routes/borrow.tsx
- app/src/routes/home.tsx
- app/src/routes/login.tsx
> fix: borrow flow during qr scanning

- app/src/routes/return.tsx
- app/src/styles/QRScanner.css
This PR is a front-end fix for the edgy buttons of the Report Modal. 
- Style
- Tests
- UI
> UI/Fix: Fixed for Unresponsive Report Page Buttons

- app/src/widgets/QrScanner/hooks.tsx
Issue: Camera stays in the active mode even when the screen says 'Camera Disabled'
Fix: incorrect usage of useEffect destructor
Lines Changed: 2
Time Spent: 2 hours 😭 
- Style
- Tests
- UI
> Fix/Camera stays on in 'Disabled' mode

- app/src/routes/return.tsx
- app/src/test/return.test.tsx
- app/src/widgets/QrScanner/hooks.tsx
- app/src/widgets/bottomTextInput.tsx
Created UI tests for the Return page.
- Style
- Tests
- UI
> Testing/Return Page

- app/src/contexts/AuthContext.tsx
> Hotfix for session-token

- app/src/routes/home.tsx
> Remove waste diverted value for now

- app/src/admin/adminApi.ts
- app/src/routes/borrow.tsx
- app/src/routes/return.tsx
- app/src/styles/header.css
- app/src/widgets/appHeader.tsx
- backend/src/controllers/dish.ts
> undo accidental commit
